sudo: false
language: node_js
node_js:
- '4'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
branches:
  only:
  - master
  - dev
before_install:
- openssl aes-256-cbc -K $encrypted_d6be824c40c2_key -iv $encrypted_d6be824c40c2_iv
  -in gae-client-secret.json.enc -out gae-client-secret.json -d
- npm rebuild
install:
- npm run build
deploy:
  provider: gae
  keyfile: "gae-client-secret.json"
  project: "quantum-enigma-707"
