application: jamesjnadeau
version: 3
runtime: php
api_version: 1
threadsafe: true


handlers:
- url: /files
  static_dir: files
  application_readable: true

- url: /(.*\.css)
  mime_type: text/css
  static_files: \1
  upload: static/(.*\.css)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: \1
  upload: static/(.*\.js)

- url: /.*
  script: index.php
