application: jamesjnadeau
version: 8
runtime: php55
api_version: 1
threadsafe: true

default_expiration: "7d"

handlers:
- url: /files
  build_dir: build/files
  application_readable: true

- url: /wind/
  build_files: build/wind/index.html
  upload: build/wind/index.html

- url: /wind
  build_dir: build/wind
  application_readable: true

- url: /graph
  build_dir: build/graph


#static site server modified from: https://gist.github.com/darktable/873098
- url: /(.*\.(appcache|manifest))
  mime_type: text/cache-manifest
  build_files: build/\1
  upload: build/(.*\.(appcache|manifest))
  expiration: "0m"

- url: /(.*\.atom)
  mime_type: application/atom+xml
  build_files: build/\1
  upload: build/(.*\.atom)
  expiration: "1h"

- url: /(.*\.crx)
  mime_type: application/x-chrome-extension
  build_files: build/\1
  upload: build/(.*\.crx)

- url: /(.*\.css)
  mime_type: text/css
  build_files: build/\1
  upload: build/(.*\.css)

- url: /(.*\.eot)
  mime_type: application/vnd.ms-fontobject
  build_files: build/\1
  upload: build/(.*\.eot)

- url: /(.*\.htc)
  mime_type: text/x-component
  build_files: build/\1
  upload: build/(.*\.htc)

- url: /(.*\.html)
  mime_type: text/html
  build_files: build/\1
  upload: build/(.*\.html)
  expiration: "1h"

- url: /(.*\.ico)
  mime_type: image/x-icon
  build_files: build/\1
  upload: build/(.*\.ico)
  expiration: "7d"

- url: /(.*\.js)
  mime_type: text/javascript
  build_files: build/\1
  upload: build/(.*\.js)

- url: /(.*\.json)
  mime_type: application/json
  build_files: build/\1
  upload: build/(.*\.json)
  expiration: "1h"

- url: /(.*\.m4v)
  mime_type: video/m4v
  build_files: build/\1
  upload: build/(.*\.m4v)

- url: /(.*\.mp4)
  mime_type: video/mp4
  build_files: build/\1
  upload: build/(.*\.mp4)

- url: /(.*\.(ogg|oga))
  mime_type: audio/ogg
  build_files: build/\1
  upload: build/(.*\.(ogg|oga))

- url: /(.*\.ogv)
  mime_type: video/ogg
  build_files: build/\1
  upload: build/(.*\.ogv)

- url: /(.*\.otf)
  mime_type: font/opentype
  build_files: build/\1
  upload: build/(.*\.otf)

- url: /(.*\.rss)
  mime_type: application/rss+xml
  build_files: build/\1
  upload: build/(.*\.rss)
  expiration: "1h"

- url: /(.*\.safariextz)
  mime_type: application/octet-stream
  build_files: build/\1
  upload: build/(.*\.safariextz)

- url: /(.*\.(svg|svgz))
  mime_type: images/svg+xml
  build_files: build/\1
  upload: build/(.*\.(svg|svgz))

- url: /(.*\.swf)
  mime_type: application/x-shockwave-flash
  build_files: build/\1
  upload: build/(.*\.swf)

- url: /(.*\.ttf)
  mime_type: font/truetype
  build_files: build/\1
  upload: build/(.*\.ttf)

- url: /(.*\.txt)
  mime_type: text/plain
  build_files: build/\1
  upload: build/(.*\.txt)

- url: /(.*\.unity3d)
  mime_type: application/vnd.unity
  build_files: build/\1
  upload: build/(.*\.unity3d)

- url: /(.*\.webm)
  mime_type: video/webm
  build_files: build/\1
  upload: build/(.*\.webm)

- url: /(.*\.webp)
  mime_type: image/webp
  build_files: build/\1
  upload: build/(.*\.webp)

- url: /(.*\.woff)
  mime_type: application/x-font-woff
  build_files: build/\1
  upload: build/(.*\.woff)

- url: /(.*\.xml)
  mime_type: application/xml
  build_files: build/\1
  upload: build/(.*\.xml)
  expiration: "1h"

- url: /(.*\.xpi)
  mime_type: application/x-xpinstall
  build_files: build/\1
  upload: build/(.*\.xpi)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  build_files: build/\1
  upload: build/(.*\.(bmp|gif|ico|jpeg|jpg|png))

# audio files
- url: /(.*\.(mid|midi|mp3|wav))
  build_files: build/\1
  upload: build/(.*\.(mid|midi|mp3|wav))  

# windows files
- url: /(.*\.(doc|exe|ppt|rtf|xls))
  build_files: build/\1
  upload: build/(.*\.(doc|exe|ppt|rtf|xls))

# compressed files
- url: /(.*\.(bz2|gz|rar|tar|tgz|zip))
  build_files: build/\1
  upload: build/(.*\.(bz2|gz|rar|tar|tgz|zip))

# index files
- url: /(.+)/
  build_files: build/\1/index.html
  upload: build/(.+)/index.html
  expiration: "15m"

- url: /(.+)
  build_files: build/\1/index.html
  upload: build/(.+)/index.html
  expiration: "15m"

# site root
- url: /
  build_files: build/index.html
  upload: build/index.html
  expiration: "15m"
