application: jamesjnadeau
version: 6
runtime: php
api_version: 1
threadsafe: true

default_expiration: "7d"

handlers:
- url: /files
  static_dir: files
  application_readable: true

- url: /themes/(.+)/assets/(.+)
  static_files: themes/\1/assets/\2
  upload: themes/(.+)/assets/(.+) 

- url: /wind/
  static_files: wind/index.html
  upload: wind/index.html

- url: /wind
  static_dir: wind
  application_readable: true

- url: /graph
  static_dir: graph

- url: /.*
  script: index.php
